#端口号
server:
  port: 9090

#设置文件上传限制
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

#阿里云oss存储相关
aliyun:
  oss:
    endpoint: oss-cn-xxx.aliyuncs.com
    access-key-id: access-key-id
    access-key-secret: access-key-secret
    bucket-name: bucket-name

